### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by christowiz** [BCJTI/file-smart-reopener-vscode#4]
- Issue Type: `Bug`
- Extension Name: `file-smart-reopener-vscode`
- Extension Version: `0.0.1`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.37.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 27,
		"activateCallTime": 1,
		"activateResolvedTime": 21,
		"activationEvent": "workspaceContains:package.json"
	},
	"runtimeErrors": []
}
```

**Comment by christowiz** [comment]
1 uncaught error. This was all the info I got from the editor.  Not sure if it helps.

**Comment by Bigous** [comment]
But, what was the error?

**Comment by Bigous** [comment]
Anyway, after tabs (which is available since 2016), it's now part of the core VSCode and the extension is not necessary.

**Comment by christowiz** [comment]
Sorry @Bigous.  I thought the VS Code process was weird to submit an issue and all it did was copy some json.  Thanks.

**Comment by Bigous** [comment]
No problem :) Do you think this extension is useful yet? If so, can you explain so I get motivated to update/upgrade and move on?
